<?php

namespace AppBundle\Entity;

/**
 * InterestRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InterestRepository extends \Doctrine\ORM\EntityRepository
{
}
