<?php

namespace AppBundle\Entity;

/**
 * UserInterestRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserInterestRepository extends \Doctrine\ORM\EntityRepository
{
}
